### ISSUE TITLE
Options for customisations

### ISSUE THREAD

**Issue by danieltomasz** [vanakat/zotero-bridge#1]
Hi! Really A really  nice plugin! I found about this plugin through newsletter!
Do you consider adding option for customisation, like adding first author and year into the markdown link?

**Comment by MunGell** [comment]
Hi @danieltomasz 

Thanks for the feedback! I was not aware of the newsletter, would appreciate if you could point me to it :)

I was thinking about configurations, but wanted to get the feedback and request for it first.
I've taken a note on your request and will try to come up with a solution asap.
If you already have a solution in mind - please feel free to suggest in a pull request.

**Comment by danieltomasz** [comment]
Thanks for the fast response:) 
By newsletter I meant Obsidian roundup :) https://www.obsidianroundup.org/2022-05-28/

I dont know much about plugin development, but in other plugins the simplest option is to have a settings pane where you could set predefined field like `@{{citekey}} {{title}}` to define the name of the file;
 it may be hard to extract a only one author and year, for me  if I could add the citekey (authorYear in my case) it will satisfy my use case and it might be much easier  to implement

**Comment by MunGell** [comment]
Hi @danieltomasz 

I've just released v1.1.0 with configuration options.

Could you please check it out and let me know if it works and if it covers your use case?

**Comment by danieltomasz** [comment]
Thats great,  thank you!
For some item this doesnt work,

For example when I have {{key}} {{title}}  I am getting
```
[B3NNCD84 - Modality-specific tracking of attention and sensory statistics in the human electrophysiological spectral exponent](zotero://select/library/items/B3NNCD84)
```
instead of 
```
[Waschke2021 - Modality-specific tracking of attention and sensory statistics in the human electrophysiological spectral exponent](zotero://select/items/B3NNCD84)
```
For some of the items I am getting
```
 [I4ZCPENW - Griffiths et al. - 2019 - Alphabeta power decreases track the fidelity of stimulus-specific information.pdf](zotero://select/library/items/I4ZCPENW)
```
Instead of the name of the item the title of the pdf file is used, but the item in Zotero has completely normal parent item.

**Comment by MunGell** [comment]
`{{ key }}` template variable prints Zotero built-it key (e.g. `B3NNCD84`).

Am I right to assume that `Waschke2021` in your case is a citekey generated by Bibtex (or similar) Zotero plugin?

[ZotServer](https://github.com/MunGell/ZotServer) (and hence this plugin) doesn't have access to Bibtex generated content (yet?), so it can't pull it to a variable.

As a workaround you can try to re-create a citekey format by using `{{firstAuthor.lastName}}{{ date.year }} - {{ title }}` template. Please let me know if this works for you!

On the second point about links to PDF instead of the parent item – I think it might be due to the fact that `zotero-obsidian` can't distinguish between parent and child items and shows them all in one list. I believe these should be 2 items with similar name - one parent item and one child PDF document. 

I will work on getting it sorted in the next version as I am impacted by the same problem as you :)

**Comment by danieltomasz** [comment]
AD1 - This was my fault, I wrongly assume the key was citekey.

Current solution is ok for my use.

If you still  want  to implement bibtex this might be useful for you 
https://github.com/melat0nin/zotero-roam-export/search?q=citekey
or https://github.com/wbthomason/zotodo/blob/3471396f19af990c602f89ca70c03c8adeb2a7f7/content/zotodo.ts#L618
EDIT: Sorry you connecting to Zotero through Zotserver, not directly, so my links might be irrelevant

**Comment by MunGell** [comment]
Thank you for the links, I will have a look to see if I can implement it in ZotServer and then in here as well!

I will close this issue as resolved, but please feel free to open a new one if you will have more feedback or feature requests!
